### ISSUE TITLE
Uso do MD5

### ISSUE THREAD

**Issue by joaolcaas** [lucaswilker14/2V-backend#1]
https://github.com/lucaswilker14/2V-backend/blob/38a36718dd3b36c7a005728b117edd63f25f6413/src/user/user.model.js#L79

Para encriptar a senha, o uso do md5 ainda está em ação. Por vários motivos visto em sala, por questão de segurança, isso deve ser mudado.

**Comment by lucaswilker14** [comment]
Feito!
